### ISSUE TITLE
Save tree into Postgres database

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#104]
I am trying to save into database the tree with nodes and I got exception.
The tree consist of  3 nodes, linear connected: 1. node is parent of 2. node and 3. node has second node as parent.
Each node has property "Id" (int), "ParentId" (nullable int), "Stage" (int) and "TreeId" (int).
Currently I set each "Id" property to negative unique integer and "ParentId" to either null or to corresponding parent node "Id".
The exception started when I moved to the latest version.
I am using PostgreSQL 11.

Here is content of exception: 
Vita.Entities.DataAccessException: 23503: insert or update on table "SpectralTreeNode" violates foreign key constraint "FK_PgSpectralTreeNode_ParentNode" ---> Npgsql.PostgresException: 23503: insert or update on table "SpectralTreeNode" violates foreign key constraint "FK_PgSpectralTreeNode_ParentNode"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 973
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlDataReader.<NextResult>d__44.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 468
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 306
   at Npgsql.NpgsqlCommand.<ExecuteReaderAsync>d__102.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__92.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 977
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 959
   at Vita.Data.Driver.DbDriver.ExecuteCommand(IDbCommand command, DbExecutionType executionType)
   --- End of inner exception stack trace ---
   at Vita.Data.Runtime.Database.ExecuteDataCommand(DataCommand command)
   at Vita.Data.Runtime.Database.SaveTableGroupRecordsOneByOne(DbUpdateTableGroup tableGrp, DataConnection conn, DbUpdateSet updateSet)
   at Vita.Data.Runtime.Database.SaveChangesNoBatch(DbUpdateSet updateSet)
   at Vita.Data.Runtime.Database.SaveChanges(EntitySession session)
   at Vita.Entities.Runtime.EntitySession.SubmitChanges()
   at Vita.Entities.Runtime.EntitySession.SaveChanges()
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgSpectralTreeUow.<>c__DisplayClass10_0.<SaveInternal>b__0() in F:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgSpectralTreeUow.cs:line 758
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.Measure[T,TResult](Func`1 func, TimeSpan& timeSpan) in F:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 221
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.MeasureTime[TResult](Func`1 func, TimeSpan& timeSpan) in F:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 236
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgSpectralTreeUow.SaveInternal(IDomainIdentifiable`1 compoundId, SpectralTreeDto dto, IEntitySession session, Boolean updateInternalCache) in F:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgSpectralTreeUow.cs:line 501
Exception data (Vita.Entities.DataAccessException): 
  DbCommand = CommandType: Text
CommandText: 
INSERT INTO tree."SpectralTreeNode" 
    ("Stage", "TreeId", "ParentNodeId")
    VALUES 
    (@P0, @P1, @P2)
 RETURNING "Id";

Parameters: 
    @P0 = 2
    @P1 = 4843
    @P2 = -1
    @P3 = 0

 
Exception data (Npgsql.PostgresException): 
  Severity = ERROR 
  InvariantSeverity = ERROR 
  SqlState = 23503 
  **MessageText = insert or update on table "SpectralTreeNode" violates foreign key constraint "FK_PgSpectralTreeNode_ParentNode"** 
  **Detail = Key (ParentNodeId)=(-1) is not present in table "SpectralTreeNode".** 
  SchemaName = tree 
  TableName = SpectralTreeNode 
  ConstraintName = FK_PgSpectralTreeNode_ParentNode 
  File = ri_triggers.c 
  Line = 2851 
  Routine = ri_ReportViolation

**Comment by rivantsov** [comment]
OK, let's see. I assume all these entities Id is identity (auto-inc) column. Batch mode is off, entities are saved one-by-one - because (as far as I remember) Pg does not support out params in dynamic SQLs, so Vita automatically turns off batch mode. In prev version, we used stored procs, and Pg allows out params for procs, just not for parameterized SQL.
The ParentNodeId (@p2) is clearly -1, had not been propagated from previous insert of the parent; it should have been. Now, you mention that you explicitly "... set ParentId to.." - that might be a problem, my first guess. First, how you set it? I assume ParentId is hidden behind entity-type ref property which you set to reference to parent ENTITY, right? once entities are connected before SaveChanges, Vita should figure out FK connections and propagate generated IDs.
Please give some more details. what's the arrangement at entity level?

**Comment by suchym** [comment]
I tried to reset negative "Id" to 0 before calling SaveChanges, but without
success. The error pointed out to 0 on "ParentId" which violates foreign
key constraints again.

I think the entities are being sent to the server in the wrong order. The
first is sent entity that represents node at second stage, parent entity is
unknown so the "ParentId" is untouched, regardless whether I reset values
or keep them untouched (-1<-> 0).

See, please, this issue. It is about the same entity.
https://github.com/rivantsov/vita/issues/61




št 28. 11. 2019 o 17:39 Roman Ivantsov <notifications@github.com>
napísal(a):

**Comment by rivantsov** [comment]
DB update code is supposed to figure out the correct order, it uses entity refs and entity state (new or modified) to figure out the order; what complicates here is identity PKs. I looked at entity def, there's a lot there, even CascadeDelete. 
 You say everything worked before, and nothing changed in your code. I'm a bit puzzled, hard to say from this info. What is IEntity? can you step-in into SaveChanges method, and trace it to the call that sorts the records? and then see why it's not sorted. Also would like to look at the code that creates these nodes (enitities) and arranges all the links, before it call SaveChanges

**Comment by rivantsov** [comment]
any more info on this? any clues to help me figure it out?

**Comment by suchym** [comment]
The VITA project was postponed. I am working on another project.
During Christmas I will find time to investigate the problem.
I will let you know when I know something new.

**Comment by suchym** [comment]
So I took the time to look at the problem of storing self-referenced entities.

The document describes what I found out. If you have any questions, please, feel free to ask.

[Document1.pdf](https://github.com/rivantsov/vita/files/3950740/Document1.pdf)

**Comment by rivantsov** [comment]
ok, got it, don't know yet what the bug is, but it's clear where to look. Will try to repro with similar setup and let you know
thanks so much!

**Comment by rivantsov** [comment]
found it, will be fixing soon

**Comment by suchym** [comment]
Thank you.

št 12. 12. 2019 o 15:12 Roman Ivantsov <notifications@github.com>
napísal(a):

**Comment by rivantsov** [comment]
done, fix pushed
