### ISSUE TITLE
Error when using Lock with MySQL

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#147]
Hi,

I have encountered an exception when using lock with **MySQL**. Btw, it works fine with **SQLite**.

Exception thrown: 'Vita.Entities.DataAccessException' in Vita.dll
An exception of type 'Vita.Entities.DataAccessException' occurred in Vita.dll but was not handled in user code
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1 OFFSET 0' at line 5

~~~C#
 // Exception with MySQL. OK with SQLite.
 return session.EntitySet<ISequenceNumber>(LockType.ForUpdate).Where(x => x.Id == id && x.TenantId == 
tenantId).FirstOrDefault();
~~~

~~~C#
// OK for both MySQL and SQLite.
return session.EntitySet<ISequenceNumber>().Where(x => x.Id == id && x.TenantId == tenantId).FirstOrDefault();
~~~

Could this be a bug, or any settings required for MySQL?

Thank you very much!

**Comment by rivantsov** [comment]
most likely a bug, in SQL lock clause formatting in combination with WHERE. Can you pls provide full SQL executed? either through operation log or somewhere inside exception there must be full SQL statement (check exc properties and exc.Data dictionary)

**Comment by jasonlaw** [comment]
==== Error Log Started 10/10/2020 8:33:17 AM ===========
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1 OFFSET 0' at line 5 
[10/10/2020 8:34:37 AM] ErrorKind:Internal 
Vita.Entities.DataAccessException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1 OFFSET 0' at line 5
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1 OFFSET 0' at line 5
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Vita.Data.Driver.DbDriver.ExecuteCommand(IDbCommand command, DbExecutionType executionType)
   --- End of inner exception stack trace ---
   at Vita.Data.Driver.DbDriver.ExecuteCommand(IDbCommand command, DbExecutionType executionType)
   at Vita.Data.MySql.MySqlDbDriver.ExecuteCommand(IDbCommand command, DbExecutionType executionType)
   at Vita.Data.Runtime.Database.ExecuteDataCommand(DataCommand command)
Exception data (Vita.Entities.DataAccessException): 
  DbCommand = CommandType: Text
CommandText: SELECT  "TenantId", "Id", "LastNumber", "UpdatedOn"
FROM "communityv3devjason"."SequenceNumber"
WHERE "Id" = @P0 AND "TenantId" = @P1
 FOR UPDATE
 LIMIT 1 OFFSET 0 ;
Parameters: 
    @P0 = "ICommunity"
    @P1 = ""

 
Exception data (MySql.Data.MySqlClient.MySqlException): 
  Server Error Code = 1064

**Comment by rivantsov** [comment]
Ok, for SQLite it's clear, it does not have any actual locks;
for MySql, I think the cause is that Limit/offset is not allowed with FOR Update clause. So just inject ToList() before FirstOrDefault
this will for execution of query with lock but without limit/offset and will return list with 1 element. Then FirstOrDefault will apply to this list on client side (Linq to objects)

**Comment by jasonlaw** [comment]
Thanks for the swift reply, it is working with your suggestion. 👍
