### ISSUE TITLE
Equal operator for entities with composite key is not supported

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#151]
I have composite primary key entity, and it would failed if using it in the where clause comparison.
Do you think this is a bug or something not avoidable?

~~~C#
    if (!string.IsNullOrEmpty(searchParams.VisitMemberId))
            {
                var mic = session.GetMemberInCommunity(searchParams.VisitMemberId, community);
                where = where.And(x => x.VisitMember == mic);
            }
~~~

~~~C#
  [Entity]
    [PrimaryKey(MemberNames = "Member,Community")]
    public interface IMemberInCommunity
    {
        [CascadeDelete]
        IMember Member { get; set; }

        [CascadeDelete]
        ICommunity Community { get; set; }

        int Admin { get; set; }

        [Size(100)]
        string Address { get; set; }
    }
~~~

~~~ C#
Vita.Data.Linq.Translation.LinqTranslationException
  HResult=0x80131500
  Message=Linq to SQL translation failed, invalid expression: Equal operator for entities with composite key is not supported. Expression: x.VisitMember.
  Source=Vita
  StackTrace:
   at Vita.Data.Linq.LinqEngine.Translate(LinqCommand command)
   at Vita.Data.Sql.SqlFactory.GetLinqSql(LinqCommand command)
   at Vita.Data.Runtime.Database.ExecuteLinqSelect(EntitySession session, LinqCommand command, DataConnection conn)
   at Vita.Data.Runtime.Database.ExecuteLinqCommand(EntitySession session, LinqCommand command)
   at Vita.Data.Runtime.DataSource.ExecuteLinqCommand(EntitySession session, LinqCommand command)
   at Vita.Entities.Runtime.EntitySession.ExecuteLinqCommand(LinqCommand command, Boolean withIncludes)
   at Vita.Entities.Runtime.EntitySession.ExecuteQuery(Expression expression)
   at Vita.Entities.Runtime.EntitySession.ExecuteQuery[TResult](Expression expression)
   at Vita.Data.Linq.EntityQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Vita.Entities.Model.EntityQuery`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Vita.Entities.Runtime.SearchHelper.ExecuteSearchImpl[TEntity](EntitySession session, Expression`1 where, SearchParams searchParams, Expression`1 include, QueryOptions options, Dictionary`2 nameMapping)
   at Vita.Entities.Runtime.SearchHelper.ExecuteSearchImpl[TEntity,TResult](EntitySession session, Expression`1 where, SearchParams searchParams, Func`2 converter, Expression`1 include, QueryOptions options, Dictionary`2 nameMapping)
   at Vita.Entities.EntitySessionExtensions.ExecuteSearch[TEntity,TResult](IEntitySession session, Expression`1 where, SearchParams searchParams, Func`2 converter, Expression`1 include, QueryOptions options, Dictionary`2 nameMapping)
   at Vita.Entities.EntitySessionExtensions.ExecuteSearch[TEntity](IEntitySession session, Expression`1 where, SearchParams searchParams, Expression`1 include, QueryOptions options, Dictionary`2 nameMapping)
   at VIQCore.Community.VisitorExtensions.SearchVisitor(IEntitySession session, VisitorSearchParams searchParams) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Modules\Visitor\VisitorExtensions_Search.cs:line 67
   at VIQCore.Community.Controllers.VisitorController.Search(VisitorSearchParams searchParams) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Controllers\VisitorController.cs:line 29
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: Equal operator for entities with composite key is not supported. Expression: x.VisitMember.
~~~

**Comment by rivantsov** [comment]
well, looks like this is by design, partially because I thought there's simple workaround: 
where(x => x.VisitMember.Member.Id == mic.Member.Id && x.VisitMember.Community.Id == mic.Member.Community.Id)
- just spell out equal expression for key members

**Comment by jasonlaw** [comment]
Alright, thanks for the clarification!
