### ISSUE TITLE
Error after upgrade Vita.Data.MySql to 3.0.5

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#155]
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'MySql.Data, Version=8.0.22.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d'. The system cannot find the file specified.
  Source=Vita.Data.MySql
  StackTrace:
   at Vita.Data.MySql.MySqlDbDriver.CreateConnection(String connectionString)
   at Vita.Data.DbExtensions.CheckConnectivity(DbDriver driver, String connectionString)
   at Vita.Data.DbExtensions.CheckConnectivity(DbSettings dbSettings, Boolean rethrow)
   at Vita.Entities.EntityApp.ConnectToDatabase(DbSettings dbSettings)
   at Vita.Entities.EntityApp.ConnectTo(DbSettings dbSettings)
   at VIQCore.VIQCore.CreateEntityApp[T](IConfiguration config) in C:\JSL\VIQCore\2020Net\viqcore_net\ViqCore\VIQCore.cs:line 33
   at VIQCore.VIQCoreWebExtensions.AddVIQCore[T](IServiceCollection services, IConfiguration configuration) in C:\JSL\VIQCore\2020Net\viqcore_net\ViqCore\Web\VIQCoreWebExtensions.cs:line 33
   at VIQCore.Community.Startup.ConfigureServices(IServiceCollection services) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Startup.cs:line 22
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at VIQCore.Community.Program.Main(String[] args) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Program.cs:line 16

**Comment by rivantsov** [comment]
8.0.22 is correct version of MySql; Vita.Data.MySql driver references it. Check all references you have in your app (package refs), and update them to this version

**Comment by jasonlaw** [comment]
After install the MySql.Data it works now.
Didn't aware we need to install MySql.Data explicitly, it works without it before.
Thanks anyway.

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

With MySQL.Data installed, it is running well with the debug mode, but giving error when publishing.
I understand this has nothing to do with VITA, but just curious had you encountered the same issue, and how did you fix it?
Thanks in advance.

~~~C#
Severity	Code	Description	Project	File	Line	Suppression State
Error		Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 VIQCore.Community -> MySql.Data 8.0.22 -> BouncyCastle.NetCore 1.8.3 -> NETStandard.Library 1.6.0 -> System.IO.FileSystem 4.0.1 -> runtime.unix.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0) 
 VIQCore.Community -> MySql.Data 8.0.22 -> BouncyCastle.NetCore 1.8.3 -> NETStandard.Library 1.6.0 -> System.IO.FileSystem.Primitives (>= 4.0.1)	VIQCore.Community	C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\VIQCore.Community.csproj	0	
~~~

**Comment by rivantsov** [comment]
as the message suggests, reference this package directly in your app (top-level project); this kind of crap is quite common

**Comment by jasonlaw** [comment]
Thanks!
