### ISSUE TITLE
Linq to SQL translation failed, invalid expression: Equal operator for entities with composite key is not supported. 

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#156]
I understand that Linq does not support the composite key, hence, may I know what is the alternative way for this?

~~~C#
public static UserCommentResponse ToUserCommentResponse<T>(this IUserCommentable<T> commentable) where T:IUserCommentEntity
        {
            var session = EntityHelper.GetSession(commentable);
            var context = session.Context;
            var blockedMembers = session.BlockedMemberQuery();
            // Following code will hit the error
            var comments = commentable.UserComments.Where(x => !blockedMembers.Contains(x.Member)).Select(x => x.ToModel()).ToList();

            return new UserCommentResponse
            {
                UserCommentsCount = comments.Count,
                UserComments = comments
            };
        }
~~~

~~~C#
Vita.Data.Linq.Translation.LinqTranslationException
  HResult=0x80131500
  Message=Linq to SQL translation failed, invalid expression: Equal operator for entities with composite key is not supported. Expression: x.Actor.
  Source=Vita
  StackTrace:
   at Vita.Data.Linq.LinqEngine.Translate(LinqCommand command)
   at Vita.Data.Sql.SqlFactory.GetLinqSql(LinqCommand command)
   at Vita.Data.Runtime.Database.ExecuteLinqSelect(EntitySession session, LinqCommand command, DataConnection conn)
   at Vita.Data.Runtime.Database.ExecuteLinqCommand(EntitySession session, LinqCommand command)
   at Vita.Data.Runtime.DataSource.ExecuteLinqCommand(EntitySession session, LinqCommand command)
   at Vita.Entities.Runtime.EntitySession.ExecuteLinqCommand(LinqCommand command, Boolean withIncludes)
   at Vita.Entities.Runtime.EntitySession.ExecuteQuery(Expression expression)
   at Vita.Entities.Runtime.EntitySession.ExecuteQuery[TResult](Expression expression)
   at Vita.Data.Linq.EntityQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Contains[TSource](IQueryable`1 source, TSource item)
   at VIQCore.Community.CommunityModelsExtensions.<>c__DisplayClass10_0`1.<ToUserCommentResponse>b__0(T x) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Models\Community\CommunityModels_Extensions.cs:line 141
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at VIQCore.Community.CommunityModelsExtensions.ToUserCommentResponse[T](IUserCommentable`1 commentable) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Models\Community\CommunityModels_Extensions.cs:line 141
   at VIQCore.Community.Controllers.DiscussionController.AddDiscussionComment(Guid key, CommentInfo commentData) in C:\JSL\VIQCore\2020Net\viqcore_net\VIQCore.Community\Controllers\DiscussionController.cs:line 192
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: Equal operator for entities with composite key is not supported. Expression: x.Actor.
~~~

**Comment by jasonlaw** [comment]
Found a way to do it. Thanks anyway.
