### ISSUE TITLE
Error ForUpdate query

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#187]
I have a ForUpdate query which was working fine before, but it is not working now, failed at the breakpoint line.
May I know what should I check for?

![image](https://user-images.githubusercontent.com/107820/128459973-b823a64b-7f00-4084-a635-4ee698257fbd.png)

`Vita.Entities.DataAccessException
  HResult=0x80131500
  Message=Fatal error encountered during command execution.
  Source=Vita
  StackTrace:
   at Vita.Data.Runtime.Database.ExecuteDataCommand(DataCommand command)
   at Vita.Data.Runtime.Database.ExecuteLinqSelect(EntitySession session, LinqCommand command, DataConnection conn)
   at Vita.Data.Runtime.Database.ExecuteLinqCommand(EntitySession session, LinqCommand command)
   at Vita.Data.Runtime.DataSource.ExecuteLinqCommand(EntitySession session, LinqCommand command)
   at Vita.Entities.Runtime.EntitySession.ExecuteLinqCommand(LinqCommand command, Boolean withIncludes)
   at Vita.Entities.Runtime.EntitySession.ExecuteQuery(Expression expression)
   at Vita.Entities.Runtime.EntitySession.ExecuteQuery[TResult](Expression expression)
   at Vita.Data.Linq.EntityQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Vita.Entities.Model.EntityQuery`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VIQCore.Community.Core.SequenceControlExtensions.GetSequenceControl(IEntitySession session, Type type, String format, String tag) in C:\JSL\VIQCore\2021Net\VIQCommunityNET\VIQCore.Community\Core\SequenceControl\SequenceControlExtensions.cs:line 32
   at VIQCore.Community.Core.SequenceControlExtensions.GetNextFormatSequence[T](IEntitySession session, String format, String tag) in C:\JSL\VIQCore\2021Net\VIQCommunityNET\VIQCore.Community\Core\SequenceControl\SequenceControlExtensions.cs:line 63
   at VIQCore.Community.Controllers.AdminController.NewOfficer(NewUpdateOfficeRequest request) in C:\JSL\VIQCore\2021Net\VIQCommunityNET\VIQCore.Community\Controllers\AdminController.cs:line 192
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
MySqlException: Fatal error encountered during command execution.

Inner Exception 2:
MySqlException: Fatal error encountered attempting to read the resultset.

Inner Exception 3:
MySqlException: Reading from the stream has failed.

Inner Exception 4:
IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..

Inner Exception 5:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
`

**Comment by jasonlaw** [comment]
Somehow it is working now...hmm...anyway, close for now..
