### ISSUE TITLE
Bug in TestGetSchema

### ISSUE THREAD

**Issue by jholliday** [rivantsov/vita#2]
New installation on VS2015 running SQL Server 2014. All tests passed except one. It looks like both SetupHelper.Driver and SetupHelper.ConnectionString are null, and that SetupHelper.Reset is never being called.

Test Name: TestGetSchema
Test FullName: Vita.UnitTests.Basic.GetSchemaTests.TestGetSchema
Test Source: C:\Projects\vita-master\5.UnitTests\Vita.UnitTests.Basic\GetSchemaTests.cs : line 18
Test Outcome: Failed
Test Duration: 0:00:56.6168251

Result StackTrace:

at Vita.Data.Model.DbModelConfig..ctor(DbDriver driver, DbOptions options, DbNamingPolicy namingPolicy, IDictionary`2 schemaMappings) in C:\Projects\vita-master\1.Framework\Vita.Core\Data\Model\DbModelConfig.cs:line 34
at Vita.Data.DbSettings..ctor(DbDriver driver, DbOptions options, String connectionString, String schemaManagementConnectionString, DbUpgradeMode upgradeMode, DbUpgradeOptions upgradeOptions, IDbInfoService dbInfoProvider, String dataSourceName, DbNamingPolicy namingPolicy) in C:\Projects\vita-master\1.Framework\Vita.Core\PublicAPI\DbSettings.cs:line 42
at Vita.UnitTests.Basic.GetSchemaTests.TestGetSchema() in C:\Projects\vita-master\5.UnitTests\Vita.UnitTests.Basic\GetSchemaTests.cs:line 23
Result Message: 
Test method Vita.UnitTests.Basic.GetSchemaTests.TestGetSchema threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by rivantsov** [comment]
yea, I see it, already fixed some time ago, will be in the next push, hopefully this weekend

**Comment by rivantsov** [comment]
should be fixed now
