### ISSUE TITLE
DBComputed Error

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#204]
Here is my entity with DBComputed for field OutstandingAmount.
~~~C#

[Entity]
[EntitySavingEvent(nameof(BillingModule.OnSavingInvoice))]
public interface IBillingInvoice
{
    [PrimaryKey, Size(20)] string InvoiceNo { get; set; }
    IBillingAccount Account { get; set; }
    IUnit Unit { get; set; }
    [Nullable] IMemberInCommunity BillTo { get; set; }  
    [Size(200)] string Description { get; set; }
    // The amount is in cent.e.g. 100 = RM1.
    int Amount { get; set; }
    int PaidAmount { get; set; }
    [DbComputed(kind: DbComputedKind.NoColumn)]
    [SqlExpression(DbServerType.MySql, "{table}.Amount - {table}.PaidAmount")]
    [SqlExpression(DbServerType.SQLite, "{table}.Amount - {table}.PaidAmount")]
    int OutstandingAmount { get; }
    bool IsFullyPaid { get; set; }
    IList<IBillingInvoiceReceipt> Receipts { get; }
    [Utc, Auto(AutoType.CreatedOn)] DateTime CreatedOn { get; }
    [ComputedClientTime] DateTime CreatedOnClientTime { get; }
    [Auto(AutoType.CreatedBy), Size(nameof(IAuth.LoginId))] string CreatedBy { get; }
}
~~~

I have got the following error:

==== Error Log Started 12/31/2021 6:26:32 AM ===========
Exception has been thrown by the target of an invocation. 
[12/31/2021 6:27:19 AM] ErrorKind:Internal 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
   at VIQCore.Community.Proxies.BillingInvoice.get_OutstandingAmount()
   at VIQCore.Community.BillingModule.OnSavingReceipt(IBillingReceipt receipt) in C:\JSL\VIQCore\2021Net\VIQCommunityNET\VIQCore.Community\Modules\Billing\BillingModule_Trans.cs:line 61
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Aether.Entities.EntitySavingEventAttribute.SaveEvents_SavingChanges(EntityRecord record, EventArgs args) in C:\JSL\Aether\AetherAll\Aether.Net\EntityAttributes\EntitySavingEvent.cs:line 36
   at Vita.Entities.Runtime.EntitySession.OnSaving()
   at Vita.Entities.Runtime.EntitySession.SaveChanges()
   at VIQCore.Community.BillingModule.PaymentAsync(OperationContext context, PaymentRequest request) in C:\JSL\VIQCore\2021Net\VIQCommunityNET\VIQCore.Community\Modules\Billing\BillingModule.cs:line 116
   at VIQCore.Community.BillingController.PaymentAsync(PaymentRequest request) in C:\JSL\VIQCore\2021Net\VIQCommunityNET\VIQCore.Community\Controllers\BillingController.cs:line 144
   at lambda_method295(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Aether.Web.AetherWebMiddleware.InvokeAsync(HttpContext context, IAppService _) in C:\JSL\Aether\AetherAll\Aether.Net\Web\AetherWebMiddleware.cs:line 49

**Comment by rivantsov** [comment]
It looks like for some reason the result of the expr is Int64, not Int32 as expected adding two Int32 values. So you can try any of: 
1. Change OutstandingAmount to be Int64
2. Try adding some explicit conv to Init32 of result inside SQL expr, not sure what is that in MySql (or is it Sqlite?!)
3. Change the OutstandingAmount calc to c# method, not SQL expression - this I would strongly recommend, look in the books  sample app/module, there's example there of computed (not DbComputed) properties. It does NOT make sense to compute this value in SQL, only complicates everything

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

Thanks for looking into this. The reason I am using DBComputed instead of Computed property is because I would like to use it in the EntitySet where clause. :)
