### ISSUE TITLE
There is already an open DataReader associated with this Connection which must be closed first. 

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#231]
Hi @rivantsov ,

From time to time, I will hit the error:

There is already an open DataReader associated with this Connection which must be closed first. 
[02/05/2024 05:20:03] ErrorKind:Internal 
Vita.Entities.DataAccessException: There is already an open DataReader associated with this Connection which must be closed first.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.CheckState()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Vita.Data.Driver.DbDriver.ExecuteCommand(IDbCommand command, DbExecutionType executionType)
   --- End of inner exception stack trace ---
   
   May I know what could have causing this error? Any pointer for troubleshooting?

Attached also a more complete log.
[Log.txt](https://github.com/rivantsov/vita/files/14195723/Log.txt)

Thanks.

**Comment by rivantsov** [comment]
thanks for reporting this. I need some more context.  
Question - once it happens, it keeps happening in the same place, or it happens once and then next time runs ok? Also, when it happens again, is it always in the same place, or in different places as well?
Also, by looking at logs, it happens after SaveChanges, you load Company entity by Id, and then touch Member.CompanyIdentity.Vouchers list, and system tries to load the related list and that's where it blows up. One suspicion is that it has something to do with list properties auto-load. 
I admit, I have memory of seeing exactly this error in the past, not so long ago, but do not recall how I fixed it or what made it go away. And this was not on MySql, so it looks like it's not a driver problem. 
So let's crack it. Can you pls show me the c# code where error happens, with related entities? 
thanks

**Comment by jasonlaw** [comment]
Thanks for looking into this issue.
The error is happening randomly, and in different places as well, which make it very hard for me to troubleshoot.
After investigating the code, the most suspicious part is the following code:

Find the comment // SUSPECT HERE!!!
~~~C#
private void ExecuteTask(ISMSCampaign campaign, IMembership[] members, TimeSpan delay)
{
    var validMembers = members.Where(x => !x.User.IsDeleted).ToList();
    Task.Run(() =>
    {
        Task.Delay(delay).Wait();
        var session = MyApp.Instance.OpenSystemSession();
        var company = session.GetEntity<ICompany>(campaign.Company.Id);
        var maxSMS = Math.Min(validMembers.Count, company.SMS);
        if (maxSMS <= 0) return;
        int qty = 0;
        var memberIds = validMembers.Take(maxSMS).Select(x => x.CompanyIdentity.Id).ToList();
        var refresh_members = session.EntitySet<IMembership>()
                                     .Where(x => memberIds.Contains(x.CompanyIdentity.Id))
                                     .ToList();
        foreach (var member in refresh_members)
        {
            try
            {
                var voucher = session.IssueVoucher(member, campaign);
                session.SaveChanges();
                var smsText = voucher.ResolvedSMSText(campaign.Template);
                var smsCount = Helper.CalculateSmsCount(smsText);
                if (qty + smsCount > company.SMS) break;
                MyApp.SMS.Send(member.CompanyIdentity.Identity.Phone, smsText);
                qty += smsCount;
                //qty++;
            }
            catch (Exception) { }
        }
        company.Post(campaign, qty);
        session.SaveChanges();
    });
}

 public static IVoucher IssueVoucher(this IEntitySession session, IMembership member, ISMSCampaign campaign)
 {
     MyApp.AbortIf(!campaign.IsActive, "Not allowed for inactive campaign.");
     var voucher = session.NewEntity<IVoucher>();
     voucher.Member = member;
     voucher.CampaignId = campaign.Id;
     voucher.Campaign = campaign.CampaignId;
     voucher.CampaignType = CampaignType.SMS;
     voucher.Reward = campaign.Reward;
     voucher.ExpiryDate = MyApp.Now.Date.AddDays(campaign.ExpiryDays);
     voucher.Code = MyApp.GetService<IVoucherCodeService>().GenerateVoucherCode();
     voucher.Remark = campaign.Remark;

     //session.ScheduleUpdateCounter(campaign);
     return voucher;
 }
 
  public static string ResolvedSMSText(this IVoucher voucher, string template)
 {
     if (voucher.EffectiveDate.HasValue)
     {
         template = template.Replace("{&EffDate}", voucher.EffectiveDate.Value.ToString("dd/MM/yy"));
     }
     return template
             .Replace("{&Brand}", voucher.Member.Company.Brand) // SUSPECT HERE!!!!
             .Replace("{%Reward}", voucher.Reward) 
             .Replace("{&VoucherCode}", voucher.Code)
             .Replace("{&ExpDate}", voucher.ExpiryDate.ToString("dd/MM/yy"));
 }
~~~

Thanks.

**Comment by rivantsov** [comment]
Ok, we have a real suspect - threading issues. First, the Task.Run is a strange and risky call, more on it later, but this is likely no the suspect. 
Ado.net objects like DbConnection, DbCommand, and Vita session (a wrapper around them) - are single-threaded objects, and do not like switching threads - that is, if you create an object on a thread, all consequent calls should be on the same thread. 
And using tasks and all that async stuff can bring you into switched threads without you knowing it. 
Basically what happens is you start things on one thread, and then unknowingly continue on another, and things break. 

My first suspect is Task.Delay(x).Wait - don't do it in sync code, use Thread.Sleep(x); quite possible with Tasks you might end up on a different physical thread after wait, and working inside your loop - that will break everything. Strange call anyway - why you need it? if it breaks without Waiting then find the cause why it break, don't shadow it. And anyway there must be a comment there explaining the need for delay!

Second, MyApp.Sms.Send - pretty sure it is remote call, likely it is async, and you are calling it from sync code, so you have to use Wait() but with ConfigureAwait(false), to avoid thread deadlocks, something like : 

   smsClient.SendRequestAsync(sms).ConfigureAwait(false).Wait();

you know what's this 'false'? - it is 'I don't care about continuation thread', continue on any thread available. and that causes thread switch, and ruins everything. 
So my advice - either refactor everything to be Async, or - take Sms.Send calls outside the loop, put stuff in the list, and send it after the loop and working with database. 

About Task.Run() in web apps, fire-and-forget, don't wait for finish. I understand the intend. This normally does not work under Asp.net (core). When the request completes, the asp.net engine cleans up and KILLS all still active threads and tasks. If you need a long running task that continues after the request is completed, you should do it in special way. It used to be a special call IHostEnvironment.QueueUserWorkItem or smth like that in older versions, now it is something about IHostedService - research it. But in general I doubt you really need it that much 

Hope this helps
