### ISSUE TITLE
Error in ASP.NET

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#57]
I get the following in ASP.NET, but my console testing is working properly.
I have all the reference already but still got the error.
Any idea? Thanks.

System.Exception
  HResult=0x80131500
  Message=EntityApp.EntityClassProvider may not be null. Use Vita.Entities.Emit.EntityClassEmitter.CreateProvider() method from Vita.Entities.Emit assembly to create provider instance.
  Source=Vita
  StackTrace:
   at Vita.Entities.Util.Throw(String message, Object[] args) in E:\JSL\CODELAB\MyCommunity\MyCommunity\3.Vita\1.Framework\Vita\2.Operations\StaticHelpers\Util.cs:line 21
   at Vita.Entities.Util.Check(Boolean condition, String message, Object[] args) in E:\JSL\CODELAB\MyCommunity\MyCommunity\3.Vita\1.Framework\Vita\2.Operations\StaticHelpers\Util.cs:line 25
   at Vita.Entities.EntityApp.InitApp() in E:\JSL\CODELAB\MyCommunity\MyCommunity\3.Vita\1.Framework\Vita\4.Internals\Entities.Model\Construction\EntityApp_InitConnect.cs:line 23
   at Vita.Entities.EntityApp.Init() in E:\JSL\CODELAB\MyCommunity\MyCommunity\3.Vita\1.Framework\Vita\1.AppModel\EntityApp.cs:line 333
   at Codelab.MyCommunity.MyCommunityWebService.DomainAppConfig.SetupApp() in E:\JSL\CODELAB\MyCommunity\MyCommunity\Codelab.MyCommunity.MyCommunityWebService\DomainAppConfig.cs:line 26
   at TodoApi.Startup.ConfigureServices(IServiceCollection services) in E:\JSL\CODELAB\MyCommunity\MyCommunity\Codelab.MyCommunity.MyCommunityWebService\Startup.cs:line 70

**Comment by jasonlaw** [comment]
Found the problem, I should have call the following before the App.init().
domainApp.EntityClassProvider = Vita.Entities.Emit.EntityClassEmitter.CreateEntityClassProvider();
