### ISSUE TITLE
DataAccessException in DataTypes test

### ISSUE THREAD

**Issue by jholliday** [rivantsov/vita#6]
Getting the following error when attempting to run the basic tests:

Vita.dll!Vita.Entities.Runtime.EntitySession.ExecuteSelect() Line 410
{"Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified."}

Tried using Nuget to install "Microsoft.SqlServer.Types", which added a "SqlServerTypes" folder to the 100.Vita project and gave instructions for manually loading native assemblies.  But it seems more geared to EF.

**Comment by rivantsov** [comment]
I will investigate this. really strange. Do you have local install of MS SQL Server? what version/edition?

**Comment by jholliday** [comment]
Local install of SQL server 2016 developer edition.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Sep 6, 2016 at 11:25 PM -0400, "Roman Ivantsov" <notifications@github.com<mailto:notifications@github.com>> wrote:


I will investigate this. really strange. Do you have local install of MS SQL Server? what version/edition?

-

**Comment by jholliday** [comment]
I was able to get the basic tests to succeed by adding a VS2016 enumeration value and adjusting the code so that it defaults to VS2014 when that version is specified.  It was defaulting to VS2008, which caused an exception when the command object was called.

Still getting exceptions in the web project, so none of the web tests work.  Still investigating.

**Comment by jholliday** [comment]
Here is the exception detail:
[Vita-DataTypesTestException.txt](https://github.com/rivantsov/vita/files/467782/Vita-DataTypesTestException.txt)

**Comment by jholliday** [comment]
I copied the assembly from a separate machine where SQL Server 2008 was installed, and then added it as a reference in the Vita Core project.  Although it builds successfully, the TestDataTypesProviderSpecific test still fails because the assembly resolver cannot locate the assembly.

**Comment by rivantsov** [comment]
On my computer the assembly is in these folders: 
C:\Program Files\Microsoft SQL Server\120\Shared
C:\Program Files\Microsoft SQL Server\110\Shared

I have also "130" folder but it's not there, and the folder is quite small (just 2 assemblies). I have 2014 installed and I guess 110 and 120 refer to SQL 2012, it was a big change. 
So try finding similar folder and drop the assembly there

**Comment by rivantsov** [comment]
I strongly suspect that it has something to do with dev edition, I think I have Pro or standard or smth like that

**Comment by rivantsov** [comment]
also read this, the last post: 
https://social.msdn.microsoft.com/Forums/Windows/en-US/1d12865b-600a-4932-b514-188861a5ea0e/missing-sql-server-dll-microsoftsqlservertypes?forum=winformsdesigner
looks like other people have this problem as well, and it might be assembly must be in GAC, installed there by some MS intall program (not nuget)

**Comment by jholliday** [comment]
I tried copying the file to all these places, but I’m getting the same result on the TestDataTypesProviderSpecific test.  All the other tests have succeeded.  This one is still quite problematic.

Note that there is a Nuget package for “Microsoft.SqlServer.Types”.  I ran it for the 505.Vita.UnitTests.Basic project.  It creates a “SqlServerTypes” folder and then provides the following instructions:

Action required to load native assemblies
To deploy an application that uses spatial data types to a machine that does not have 'System CLR Types for SQL Server' installed you also need to deploy the native assembly SqlServerSpatial110.dll. Both x86 (32 bit) and x64 (64 bit) versions of this assembly have been added to your project under the SqlServerTypes\x86 and SqlServerTypes\x64 subdirectories. The native assembly msvcr100.dll is also included in case the C++ runtime is not installed.
You need to add code to load the correct one of these assemblies at runtime (depending on the current architecture).
ASP.NET applications
For ASP.NET applications, add the following line of code to the Application_Start method in Global.asax.cs:
    SqlServerTypes.Utilities.LoadNativeAssemblies(Server.MapPath("~/bin"));
Desktop applications
For desktop applications, add the following line of code to run before any spatial operations are performed:
    SqlServerTypes.Utilities.LoadNativeAssemblies(AppDomain.CurrentDomain.BaseDirectory);

I added the specified line of code in _Program.cs of the basic tests project, but the test is still failing.

**Comment by rivantsov** [comment]
aha! means that they were not there. 
try installing feature pack for MS SQL: 
https://www.microsoft.com/en-us/download/details.aspx?id=52676
or find version for your server type; notes say that it includes installer SqlSysClrTypes.msi that installs this assembly

**Comment by jholliday** [comment]
Installed the feature pack, but the test still fails.  Something appears to be hard-coded to version 10.0.0.0 of the assembly, which does not exist anywhere on my system.

**Comment by rivantsov** [comment]
do you still have this call in _program.cs? 
SqlServerTypes.Utilities.LoadNativeAssemblies(AppDomain.CurrentDomain.BaseDirectory);

you mentioned before you added it. Try remove/add this line

**Comment by rivantsov** [comment]
and what's the error in webtests?

**Comment by jholliday** [comment]
Tried both with and without that line.  Here is the error log:

Test Name:              TestDataTypesProviderSpecific
Test FullName:                 Vita.UnitTests.Basic.DataTypesTests.TestDataTypesProviderSpecific
Test Source: C:\Users\John\Source\Repos\vita\5.UnitTests\Vita.UnitTests.Basic\DataTypesTests.cs : line 276
Test Outcome:        Failed
Test Duration:         0:00:00.4565462

Result StackTrace:
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Data.SqlClient.SqlConnection.ResolveTypeAssembly(AssemblyName asmRef, Boolean throwOnError)
   at System.Data.SqlClient.SqlConnection.<>c__DisplayClass168_0.<CheckGetExtendedUDTInfo>b__0(AssemblyName asmRef)
   at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at System.Data.SqlClient.SqlConnection.CheckGetExtendedUDTInfo(SqlMetaDataPriv metaData, Boolean fThrow)
   at System.Data.SqlClient.SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData)
   at System.Data.SqlClient.SqlDataReader.GetValueInternal(Int32 i)
   at System.Data.SqlClient.SqlDataReader.GetValue(Int32 i)
   at System.Data.SqlClient.SqlDataReader.get_Item(Int32 i)
   at Vita.Entities.Runtime.EntityMaterializer.ReadRecord(IDataRecord dataRecord, EntitySession session) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Entities\Runtime\EntityMaterializer.cs:line 78
   at Vita.Data.Database.<>c__DisplayClass15_0.<ExecuteSelect>b__0(IDataReader reader) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Data\Database\Database.cs:line 99
   at Vita.Data.Database.ExecuteDbCommand(IDbCommand command, DataConnection connection, DbExecutionType executionType, Func`2 resultsReader) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Data\Database\Database_exec.cs:line 31
--- End of inner exception stack trace ---
    at Vita.Data.Database.ExecuteDbCommand(IDbCommand command, DataConnection connection, DbExecutionType executionType, Func`2 resultsReader) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Data\Database\Database_exec.cs:line 56
   at Vita.Data.Database.ExecuteSelect(EntitySession session, EntityCommand command, Object[] args) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Data\Database\Database.cs:line 106
   at Vita.Data.DataSource.ExecuteSelect(EntitySession session, EntityCommand command, Object[] args) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Data\DataAccessService\DataSource.cs:line 45
   at Vita.Entities.Runtime.EntitySession.ExecuteSelect(EntityCommand command, Object[] args) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Entities\Runtime\EntitySession.cs:line 410
   at Vita.Entities.Runtime.EntitySession.GetRecord(EntityKey primaryKey, LoadFlags flags) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Entities\Runtime\EntitySession.cs:line 273
   at Vita.Entities.Runtime.EntitySession.GetEntity[TEntity](Object primaryKeyValue, LoadFlags flags) in C:\Users\John\Source\Repos\vita\1.Framework\Vita.Core\Entities\Runtime\EntitySession.cs:line 136
   at Vita.UnitTests.Basic.DataTypesTests.TestMsSqlTypes() in C:\Users\John\Source\Repos\vita\5.UnitTests\Vita.UnitTests.Basic\DataTypesTests.cs:line 317
   at Vita.UnitTests.Basic.DataTypesTests.TestDataTypesProviderSpecific() in C:\Users\John\Source\Repos\vita\5.UnitTests\Vita.UnitTests.Basic\DataTypesTests.cs:line 279
Result Message:
Test method Vita.UnitTests.Basic.DataTypesTests.TestDataTypesProviderSpecific threw exception:
Vita.Entities.DataAccessException: Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by rivantsov** [comment]
ok, one surprise is that the test fails on reading the entity back, after it successfully created 2 entities, so SaveChanges ran OK (?!) in test, just 2 lines prior. But it fails when reading it back. 
I see that internally test fails in EntityMaterializer.ReadRecord. Can you please put breakpoint there inside the loop and see which column/data type actually fails?

**Comment by jholliday** [comment]
colMap.DbColumn
.ColumnName = “GeographyProp”
.GlobalName = “types.MsSqlDataTypesEntity.GeographyProp”
.TypeInfo
              .SqlTypeSpec = “geography”

**Comment by rivantsov** [comment]
OK, good news - it has nothing to do with Vita per se, it would fail if you just create a little console app and try to read the the table using ADO.NET. Good news is that it narrows down the problem. 
Bad news is that it is still a problem. I think the following article might be about your case: 
https://msdn.microsoft.com/en-us/library/dn236441(v=sql.120).aspx
Interestingly the article does not suggest a real fix, only workarounds. Try the last one - attribute in connection string.

**Comment by jholliday** [comment]
Well, using the “Type System Version” attribute in the connection string with a value of “SQL Server 2012” causes System.Data to look for Microsoft.SqlServer.Types version 11.0.0.0, which is also not present on my system.  Interestingly, a value of “Latest” which is recommended by another article, it reverts back to looking for version 10.0.0.0.  Tried “SQL Server 2014” and “SQL Server 2016”, but those values are invalid.

I also tried the second option, using a custom assemblyBinding entry in app.config.  Searching my system, I found copies of Microsoft.SqlServer.Types.dll (versions 13.0.1601.5 and 12.0.2000.8) that were deployed to the GAC by the SQLSysClrTypes installer.  However, the assemblyBinding entry is apparently ignored.  Tried every combination of these settings to no avail.

How hard would it be to selectively enable/disable the Geography data type?  Perhaps using a “DbOptions.UseGeography” enum?

**Comment by rivantsov** [comment]
Well, now we are at clear point that this MS SQL setup issue, not Vita. I suggest the following
1. Uninstall SQL Server and install different version (2012?), preferably higher edition (standard?), and see if it works
2. if this does not help, write a simple console app that uses ADO.NET to read a table with geography column - it would fail, and then take it to MS support and forums; having a small app without VITA would help to test/check your case on other computers, and hopefully MVPs and experts can figure it out
that's all I can suggest

**Comment by jholliday** [comment]
Ok – agreed.  For now, I will move forward with what I have and avoid using any of the spatial data column types.  I will also continue pursuing a solution via the MS forums, etc.
