### ISSUE TITLE
Materialized view - Count 

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#83]
I have materialized view
public interface IPgSpectraStatistics
    {
        short Postprocessing { get; set; }
        short Polarity { get; set; }
        short Analyzer { get; set; }
        byte IonActivation { get; set; }
        byte Stage { get; set; }
        byte? IonizationMethod { get; set; }
        int SpectrumCount { get; set; }
    }
SpectrumCount is aggregated count and raw view definition in PostgreSql is 'int8' data type.

This always worked until I moved to latest version and immediately got exception : 'Specified cast is not valid.'

First I thought that 'byte' is wrong (because of specific treating this type in PostgreSQL), but no. It is 'SpectrumCount'.
Because exception comes from VITA I am not able to process it or repair data.
I tried to change 'int' to 'long' but VITA raised exception that model is different. (Of course)

Then I tried upgrade schema, but the same fail - model is changed.

I deleted view from database and again tried to upgrade schema, hoping that now VITA creates new, not.
But again:
_Initializing EntityApp PgMassFrontierEntityApp.====================================
  Building entity model...
ERROR: View definition error (HighChem.MassFrontier.Data.Entities.PgSql.Modules.Spectral_Tree.Views.IPgSpectraStatistics): data type for view property 'SpectrumCount' (System.Int64 ) does not match query output property type (System.Int32) ._

Here is query definition:
__var spectrumSet = ViewHelper.EntitySet<IPgSpectrum>();
            var query = from s in spectrumSet
                        join ia in ViewHelper.EntitySet<IPgIonActivationEnergy>()
                              on s.Id equals ia.Spectrum.Id into iaSet
                        from iax in iaSet.DefaultIfEmpty()
                        join ii in ViewHelper.EntitySet<IPgInstrumentInfo>() on s.Node.SpectralTree.Id equals ii.SpectralTree.Id into iiSet
                        from iix in iiSet.DefaultIfEmpty()
                        group s by new
                        {
                            Postprocessing = s.Postprocessing,
                            Polarity = s.Polarity,
                            Analyzer = s.Analyzer,
                            IonActivation = iax.IonActivation,
                            IonizationMethod = iix.IonizationMethod,
                            Stage = s.Node.Stage

                        } into groups
                        select new
                        {
                            Postprocessing = groups.Key.Postprocessing,
                            Polarity = groups.Key.Polarity,
                            Analyzer = groups.Key.Analyzer,
                            IonActivation = groups.Key.IonActivation,
                            IonizationMethod = groups.Key.IonizationMethod,
                            Stage = groups.Key.Stage,
                            SpectrumCount = groups.Count()
                        };__

Message is quite clear.
I changed query and instead of ..groups.Count() I used groups.LongCount()
And now:
_"Object reference not set to an instance of an object."} | System.NullReferenceException
   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeNewOperator(NewExpression expression, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeLambda(Expression expression, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeQuote(Expression expression, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, Expression parameter, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeSelect(IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeQueryableCall(MethodInfo method, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeCall(MethodCallExpression expression, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, Expression parameter, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(ExpressionChain expressionChain, Expression parameter, TranslationContext context)
   at Vita.Data.Linq.LinqEngine.TranslateSelectExpression(Expression linqExpr, TranslationContext context)
   at Vita.Data.Linq.LinqEngine.TranslateSelect(LinqCommand command)
   at Vita.Data.Model.DbModelBuilder.CompileViews()
   at Vita.Data.Model.DbModelBuilder.Build()
   at Vita.Entities.EntityApp.GetCreateDbModel(DbSettings settings, IActivationLog log)
   at Vita.Entities.EntityApp.ConnectToDatabase(DbSettings dbSettings)
   at Vita.Entities.EntityApp.ConnectTo(DbSettings dbSettings)
   at HighChem.MassFrontier.Data.Entities.PgEntityAppHelper.InitApp(PgMassFrontierEntityApp app, IConnectionProvider connectionProvider, Boolean allowBatchUpdateMode, Int32 batchParamCount, Boolean allowGlobalChache, Boolean forceArraysAsLiterals, String logFilePath) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Vita.Entities.PgSql\Apps\Common\EntityAppHelper.cs:line 141_

In the past I wondered how it is possible that I define aggregated count as 'int' but backend (SQL Server and PostgreSQL) considers it as 'Long' and what would happen if the number was more than max int. 
Now it works as I expect. :) 

Do you have any idea for a solution?

**Comment by rivantsov** [comment]
wow, quite a lot of information. Thanks for reporting this, pls give me some time to digest and investigate, I will get back to you asap
what about other issues - did you resolve them?

**Comment by suchym** [comment]
I could not bypass the installation of the package. I wonder why you decided to use it instead of System.Data.SQLite. Some people on web recommend to use the package from SQLite guys. 
So far I have not compared them, so I do not know what the truth is in web talks

Now I am in transient state. Two my projects have direct reference to projects of VITA and also installed Microsoft.Data.SQLite because the dll did not apear in the bin output. As a result I had to change connection string constructing because Microsoft's does not allow nothing to set in fact. And I added this line before any connection is open:
                SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_e_sqlite3());

If you release new version I will try to resolve this problem. Now I am testing whether all works as before. 

I'm afraid of data storage tests.

That's all for now

**Comment by rivantsov** [comment]
I used MS driver for SQLite because that they had it available on .NET core, and SQLite didn't. Did it change? I agree using driver from SQLite guys is preferable; let me check again the situation

**Comment by rivantsov** [comment]
OK, I looked it up, SQLite driver from SQLite team now supports .NET STandard, since about Aug 2018; 
And it looks like it is much better long option.
I will dig more and quite possibly switch to their driver. Might take a few days

**Comment by suchym** [comment]
Sure, all right.

št 28. 3. 2019 o 17:15 Roman Ivantsov <notifications@github.com> napísal(a):

**Comment by rivantsov** [comment]
About your original Count problem and 'Invalid Cast" exception. Trying to repro it somehow.
Few questions
1. Please give me original full exc message with stack trace
2. your query (c#) is strange, ViewHelper.EntitySet<T>() requires type argument, but there's none in the query, something lost in posting
3. Please show the SQL of the query
4. Can you pls do the experiment: remove SpectrumCount prop from entity and query def, and try running it - to make sure it is the SpectrumCount problem, not some other column
I am seeing you do several outer joins, this might be related, some things come out as NULLs or non-existent rows or smth

**Comment by rivantsov** [comment]
With LongCount I already found a problem, will fix that

**Comment by suchym** [comment]
1. Here is exception:
System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=HighChem.MassFrontier.Data.Entities.Proxies
  StackTrace:
   at HighChem.MassFrontier.Data.Entities.Proxies.PgSpectraStatistics.**get_SpectrumCount()**
   at HighChem.MassFrontier.Data.Repositories.PgSql.SpectralTree.Spectrum.PgSpectrumStatisticsRepository.<GetData>d__1.MoveNext() in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\SpectralTree\Spectrum\PgSpectrumStatisticsRepository.cs:line 24

2. I agree the query is strange but the definition of query is right in my code. EntitySet is generic method. Likely paste ...
 
3. Here is view definition in Postgres:

CREATE MATERIALIZED VIEW spectrum."SpectraStatistics"
TABLESPACE "PgTest002"
AS SELECT "s$"."Postprocessing",
    "s$"."Polarity",
    "s$"."Analyzer",
    "iax$"."IonActivation",
    "iix$"."IonizationMethod",
    "t0$"."Stage",
    count(*) AS "SpectrumCount"
   FROM spectrum."Spectrum" "s$"
     JOIN tree."SpectralTreeNode" "t0$" ON "t0$"."Id" = "s$"."NodeId"
     LEFT JOIN spectrum."IonActivationEnergy" "iax$" ON "s$"."Id" = "iax$"."SpectrumId"
     LEFT JOIN tree."InstrumentInfo" "iix$" ON "t0$"."TreeId" = "iix$"."TreeId"
  GROUP BY "s$"."Postprocessing", "s$"."Polarity", "s$"."Analyzer", "iax$"."IonActivation", "iix$"."IonizationMethod", "t0$"."Stage"
WITH DATA;

-- View indexes:
CREATE UNIQUE INDEX "IXCU_PgSpectraStatistics__503031909" ON spectrum."SpectraStatistics" USING btree ("Postprocessing", "Polarity", "Analyzer", "IonActivation", "IonizationMethod", "Stage");


4. Bellow is result of the select query of materialized view.
Postprocessing	Polarity	Analyzer	IonActivation	IonizationMethod	Stage	SpectrumCount
4	2	2	11	15	3	1094
4	2	2	11	15	4	700
4	2	2	11	16	2	1326
4	2	2	11	20	2	5545
4	2	2	11	20	3	4078
4	2	2	11	20	4	2780
4	2	2	11	20	5	508
4	2	2		0	1	5
4	2	2		15	1	1527
4	2	2		16	1	162
4	2	2		20	1	378
Fourth column is IonActivation which is one of the left join entity. As you can see it is for some rows 'NULL' but but when I change it to nullable byte  in view definition interface I get following exception

_Initializing EntityApp PgMassFrontierEntityApp.====================================
  Building entity model...
ERROR: View definition error (HighChem.MassFrontier.Data.Entities.PgSql.Modules.Spectral_Tree.Views.IPgSpectraStatistics): data type for view property 'IonActivation' (System.Nullable`1[System.Byte] ) does not match query output property type (System.Byte) .
Here is view definition interface:
public interface IPgSpectraStatistics
    {
        short Postprocessing { get; set; }
        short Polarity { get; set; }
        short Analyzer { get; set; }
        **byte? IonActivation { get; set; }**  --exception above described
        byte Stage { get; set; }
        byte? IonizationMethod { get; set; }
        int SpectrumCount { get; set; }
    }

When it is marked as non-nullable byte (**byte IonActivation { get; set; }**) I get exception in case when one of row contains NULL. 
I do not know what to do.

**Comment by suchym** [comment]
Here is Locals pane content:
![image](https://user-images.githubusercontent.com/22904904/55387558-ebd6eb80-5531-11e9-9594-e2f8f6098292.png)

**Comment by rivantsov** [comment]
Update on progress: moved to SQLite driver from SQLite team, everything seems to be working. Now to views and mat views. Expect all by end of week

**Comment by rivantsov** [comment]
should be fixed now
