### ISSUE TITLE
Save -PostgreSQL Exception

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#84]
As I expected I got exception during execution of session.SaveChanges(). 
I'm not aware of the changes in code for this part now.
 Te exception is:
System.Exception: Object  is not an Entity, cannot retrieve Record field.
   at Vita.Entities.Util.Throw(String message, Object[] args)
   at Vita.Entities.EntityHelper.GetRecord(Object entity)
   at Vita.Entities.Runtime.EntityRecord.RefreshIdentityReferences()
   at Vita.Data.Runtime.Database.SaveTableGroupRecordsOneByOne(DbUpdateTableGroup tableGrp, DataConnection conn, DbUpdateSet updateSet)
   at Vita.Data.Runtime.Database.SaveChangesNoBatch(DbUpdateSet updateSet)
   at Vita.Data.Runtime.Database.SaveChanges(EntitySession session)
   at Vita.Entities.Runtime.EntitySession.SubmitChanges()
   at Vita.Entities.Runtime.EntitySession.SaveChanges()
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgSpectralTreeUow.<>c__DisplayClass10_0.<SaveInternal>b__0() in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgSpectralTreeUow.cs:line 755
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.Measure[T,TResult](Func`1 func, TimeSpan& timeSpan) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 177
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.MeasureTime[TResult](Func`1 func, TimeSpan& timeSpan) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 185
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgSpectralTreeUow.SaveInternal(IDomainIdentifiable`1 compoundId, SpectralTreeDto dto, IEntitySession session, Boolean updateInternalCache) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgSpectralTreeUow.cs:line 500

Hardly help you to navigate, but if it was necessary, I make a reference to the project so we can get right to the source code.

**Comment by rivantsov** [comment]
It is Postgres, right? something with identity generation/refresh. Can you please post the definition of entity involved?

**Comment by suchym** [comment]
I do not know entity where exception occurred. I am not  able to find out name of entity from exception as you can see. But I suspect that it is the same issue as I described in issue #61. The problem was in wrong order some properties of self-referencing entity - hierarchy tree.
I can switch a package reference to the project and test it. Then I will able to provide more info including entity name. But it will take a while.

Uff, there are more issues but they seem they are on my side - mainly  type conversion exceptions. 
The origin database schema was created for MS SQL Server and moved to Postgres. There are some incompatibilities that passed in 1.9.3 version but latest version is more stricter so I must deeper test.

**Comment by rivantsov** [comment]
found it, fixing... workaround for now - it breaks on entity ref that is null, for new entity. So for this new entity do NOT assign null explicitly to property

**Comment by rivantsov** [comment]
by the way, this happens only in non-batch mode; with Pg, VITA supports batch mode, even with identities. Did you explicitly disable batch mode? (with DbSettings)
Batch mode can provide HUGE perf benefits, especially with multiple inserts.  I would advise enable it

**Comment by suchym** [comment]
Haha,  one of the biggest benefits is switched off.  I did not know. Thanks
for warning. And also for effort.

**Comment by suchym** [comment]
I had always batch mode ON I don't understand it.
If  something did not change the batch update mode is set in code : dbOptions |= DbOptions.UseBatchMode;

I think that I saw in VITA code of previous version that batch mode is OFF for PostgreSQL.

**Comment by suchym** [comment]
Another exception when trying to save fragmentation pathway to the database. The previous exception is related to saving spectral tree - another schema.
Before I  did not get any exception. It worked without problem. Extensively tested.

Here is exception:
Vita.Entities.DataAccessException: 23505: duplicate key value violates unique constraint "PK_PgUniqueStructureTopologicalIndex" ---> Npgsql.PostgresException: 23505: duplicate key value violates unique constraint "PK_PgUniqueStructureTopologicalIndex"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.<NextResult>d__46.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 490
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 340
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__100.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__92.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
   at Vita.Data.Driver.DbDriver.ExecuteCommand(IDbCommand command, DbExecutionType executionType)
   --- End of inner exception stack trace ---
   at Vita.Data.Runtime.Database.ExecuteDataCommand(DataCommand command)
   at Vita.Data.Runtime.Database.SaveChangesNoBatch(DbUpdateSet updateSet)
   at Vita.Data.Runtime.Database.SaveChanges(EntitySession session)
   at Vita.Entities.Runtime.EntitySession.SubmitChanges()
   at Vita.Entities.Runtime.EntitySession.SaveChanges()
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgFragmentationPathwayUow.<>c__DisplayClass17_0.<SaveInternal>b__0() in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgFragmentationPathwayUow.cs:line 252
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.Measure[T,TResult](Func`1 func, TimeSpan& timeSpan) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 177
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.MeasureTime[TResult](Func`1 func, TimeSpan& timeSpan) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 185
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgFragmentationPathwayUow.SaveInternal(IDomainIdentifiable`1 compoundId, FragmentationPathwayDto dto, IEntitySession session, Boolean updateInternalCache) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgFragmentationPathwayUow.cs:line 176
Exception data (Vita.Entities.DataAccessException): 
  DbCommand = CommandType: Text
CommandText: 
INSERT INTO common."UniqueStructureTopologicalIndex" 
    ("AnnotationStructureId", "Charge", "Geometry", "Basic", "NumC", "NumO", "NumN", "NumCl", "NumS", "NumSi", "NumP", "NumBr", "NumOther", "Basic1", "Basic2", "Basic3", "Basic4", "Basic5", "Basic6", "Geom1", "Geom2", "Geom3", "Geom4", "Geom5", "Geom6", "Geom7", "Geom8", "Geom9", "Geom10", "Geom11", "Geom12", "Geom13", "Geom14", "Geom15", "Geom16", "Geom17", "Geom18", "Geom19", "Geom20")
    VALUES 
    (0, 176701824, 6150, 1468176, CAST(11 AS smallint), CAST(3 AS smallint), CAST(2 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(16 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(3 AS smallint), CAST(9 AS smallint), CAST(1 AS smallint), True, True, True, False, True, False, True, True, False, False, False, True, False, False, False, False, False, False, False, False),
    (0, 0, 0, 0, CAST(11 AS smallint), CAST(3 AS smallint), CAST(2 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(16 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(3 AS smallint), CAST(9 AS smallint), CAST(1 AS smallint), True, True, True, False, True, False, True, True, False, False, False, True, False, False, False, False, False, False, False, False),
    (0, 0, 0, 0, CAST(10 AS smallint), CAST(2 AS smallint), CAST(1 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(13 AS smallint), CAST(0 AS smallint), CAST(0 AS smallint), CAST(2 AS smallint), CAST(9 AS smallint), CAST(1 AS smallint), True, True, True, False, True, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False);
Parameters: 

  DbKeyName = PK_PgUniqueStructureTopologicalIndex 
  EntityName = PgUniqueStructureTopologicalIndex 
  EntityKeyName = PK_PgUniqueStructureTopologicalIndex 
  IndexAlias =  
  MemberNames = AnnotationStructureId 
Exception data (Npgsql.PostgresException): 
  Severity = ERROR 
  SqlState = 23505 
  Code = 23505 
  MessageText = duplicate key value violates unique constraint "PK_PgUniqueStructureTopologicalIndex" 
  Detail = Key ("AnnotationStructureId")=(0) already exists. 
  SchemaName = common 
  TableName = UniqueStructureTopologicalIndex 
  ConstraintName = PK_PgUniqueStructureTopologicalIndex 
  File = nbtinsert.c 
  Line = 535 
  Routine = _bt_check_unique 

**AnnotationStructureId is 0, which should not be.**

What I changed is adding property to the 'IPgUniqueStructure' entity
[OneToOne]
        IPgUniqueStructureTopologicalIndex TopologicalIndex { get; }

Can this change affect anything?

**Comment by rivantsov** [comment]
can it affect? - I think it can... the whole thing looks really strange, 
AnnotationStructureId is a PK and is identity? but Vita tries to use INSERT with multiple rows - which should not be happening I think, with multiple rows we cannot retrieve individual generated IDs for each record. 
And I wonder how it supposed to work, IPgUniqueStructure should be inserted right in the same trans, and get the generated identity from parent rec, as its own ID? not sure it works, but for sure this scenario is not tested (with identities all over the place). 
If you say it worked before, then you added OneToOne link on other table, and it broke? Then let's not do this, I think. I will double check inserting identities with multi-record insert, but it should not be allowed, might be a bug

**Comment by suchym** [comment]
IPgUniqueStructure  has no parent entity. It is separate branch. Only other entity(ies) are referenced to it and keep reference to AnnotationStructureId. There is no cascade deletes between these entities. When referenced entity is deleted it does not delete underlying IPgUniqueStructure because they are unique across database. It has only one underlying entity IPgUniqueStructureTopologicalIndex which has relation on-to -one to parent entity and cascade delete which means when IPgUniqueStructure  is deleted then also topological index is deleted but this does not occurs because the system does not do this.

I did not want perform any changes in schema but I had to do - exceptions from VITA. My motivation to move VITA .NET Standard is access to npgsql driver version 4 due to support of composite , json  and  range types. I tried to move VITA 1.9. to npgsql 4 but it did not work because VITA did not load schema at start up. I was not able to resolve it. I hoped that moving to new version will be more seamless.

**Comment by rivantsov** [comment]
If I got it right, looks like OneToOne should be in different place - on IPgUniqueStructureTopIndex, on a property referencing IPgUniqueStructure. 
OneToOne is placed on a child entity, it's reference to parent, basically saying: "This is my parent ref, and it is my PK at the same time". So if you have IMyEntity (parent), and IMyEntityDetails which is 1-1 'extension', you put ref to IMyEntity on IMyEntityDetails with OneToOne attr
Well, sorry for troubles, we will figure it out, don't worry. Just give me a few days. But one definite factor that is a source of troubles - Identities.  Man, you should have moved to Guids when it was early enough. 
I was a bit busy with other stuff, now will focus on this, we should fix it all by the end of the week.

**Comment by rivantsov** [comment]
just pushed new version 2.3, everything should be fixed (except sizes in modules), 
hopefully all fixed - could not create materialized view like yours, but tried similar things

**Comment by rivantsov** [comment]
Hi again,
did you have a chance to test it?

**Comment by suchym** [comment]
Sorry, I am sick.
 I try the new version next week.

**Comment by rivantsov** [comment]
Ah, sorry to hear this, get well soon! no rush, just let me know when you run into problems
get well!

**Comment by suchym** [comment]
I finally got to test data storage in Vita 2.3. 
I would like to ask if it is expected switched off  the 'batch update' mode  in PostgreSQL? 
In the exception text I can see the procedure call (Vita.Data.Runtime.Database.SaveChangesNoBatch), which indicate me that this mode is turned off, although I turned it on when the application was initialized.

Here is the exception I got during test:

Vita.Entities.DataAccessException: 23503: insert or update on table "Peak" violates foreign key constraint "FK_PgSpectrumPeak_Spectrum" ---> Npgsql.PostgresException: 23503: insert or update on table "Peak" violates foreign key constraint "FK_PgSpectrumPeak_Spectrum"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.<NextResult>d__46.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 490
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 340
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__100.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__92.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
   at Vita.Data.Driver.DbDriver.ExecuteCommand(IDbCommand command, DbExecutionType executionType)
   --- End of inner exception stack trace ---
   at Vita.Data.Runtime.Database.ExecuteDataCommand(DataCommand command)
   at Vita.Data.Runtime.Database.SaveChangesNoBatch(DbUpdateSet updateSet)
   at Vita.Data.Runtime.Database.SaveChanges(EntitySession session)
   at Vita.Entities.Runtime.EntitySession.SubmitChanges()
   at Vita.Entities.Runtime.EntitySession.SaveChanges()
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgSpectralTreeUow.<>c__DisplayClass10_0.<SaveInternal>b__0() in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgSpectralTreeUow.cs:line 755
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.Measure[T,TResult](Func`1 func, TimeSpan& timeSpan) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 177
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.MeasureTime[TResult](Func`1 func, TimeSpan& timeSpan) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 185
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgSpectralTreeUow.SaveInternal(IDomainIdentifiable`1 compoundId, SpectralTreeDto dto, IEntitySession session, Boolean updateInternalCache) in D:\Dev\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgSpectralTreeUow.cs:line 500
Exception data (Vita.Entities.DataAccessException): 
  DbCommand = CommandType: Text
CommandText: 
INSERT INTO spectrum."Peak" 
    ("SpectrumId", "OrderId", "Mz", "Abundance", "Accuracy", "Resolution", "PeakFlag")
    VALUES 
    (-1, 26, 285.0221, 3.694324, 0, 0, CAST(0 AS bigint)),
    (-1, 25, 219.0438, 0.723589, 0, 0, CAST(0 AS bigint)),
    (-1, 24, 191.9647, 0.590931, 0, 0, CAST(0 AS bigint)),
    (-1, 23, 184.0757, 0.619071, 0, 0, CAST(0 AS bigint)),
    (-1, 22, 174.0228, 0.751729, 0, 0, CAST(0 AS bigint)),
    (-1, 21, 158.008, 3.891301, 0, 0, CAST(0 AS bigint)),
    (-1, 20, 157.015, 8.884065, 0, 0, CAST(0 AS bigint)),
    (-1, 19, 156.0118, 100, 0, 0, CAST(0 AS bigint)),
    (-1, 18, 132.0138, 1.515517, 0, 0, CAST(0 AS bigint)),
    (-1, 17, 130.0172, 5.656054, 0, 0, CAST(0 AS bigint)),
    (-1, 16, 120.0562, 3.095353, 0, 0, CAST(0 AS bigint)),
    (-1, 15, 110.0609, 4.904325, 0, 0, CAST(0 AS bigint)),
    (-1, 14, 109.0483, 1.181862, 0, 0, CAST(0 AS bigint)),
    (-1, 27, 287.0184, 0.840167, 0, 0, CAST(0 AS bigint)),
    (-1, 12, 96.0443, 0.623091, 0, 0, CAST(0 AS bigint)),
    (-1, 11, 93.0532, 0.731629, 0, 0, CAST(0 AS bigint)),
    (-1, 10, 92.0498, 7.702203, 0, 0, CAST(0 AS bigint)),
    (-1, 9, 79.0177, 1.057244, 0, 0, CAST(0 AS bigint)),
    (-1, 8, 78.0333, 0.727609, 0, 0, CAST(0 AS bigint)),
    (-1, 7, 68.049, 7.963499, 0, 0, CAST(0 AS bigint)),
    (-1, 6, 66.0423, 0.506512, 0, 0, CAST(0 AS bigint)),
    (-1, 5, 65.0382, 3.822962, 0, 0, CAST(0 AS bigint)),
    (-1, 4, 60.0552, 0.542692, 0, 0, CAST(0 AS bigint)),
    (-1, 3, 55.0178, 0.522592, 0, 0, CAST(0 AS bigint)),
    (-1, 2, 54.0333, 0.566811, 0, 0, CAST(0 AS bigint)),
    (-1, 1, 53.0389, 0.594951, 0, 0, CAST(0 AS bigint)),
    (-1, 13, 108.0457, 12.17237, 0, 0, CAST(0 AS bigint));
Parameters: 

 
Exception data (Npgsql.PostgresException): 
  Severity = ERROR 
  SqlState = 23503 
  Code = 23503 
  MessageText = insert or update on table "Peak" violates foreign key constraint "FK_PgSpectrumPeak_Spectrum" 
  Detail = Key (SpectrumId)=(-1) is not present in table "Spectrum". 
  SchemaName = spectrum 
  TableName = Peak 
  ConstraintName = FK_PgSpectrumPeak_Spectrum 
  File = ri_triggers.c 
  Line = 2851 
  Routine = ri_ReportViolation 

The negative SpectrumId is my labeling to identify spectrum before save. This worked well in previous version - 1.9.3.

**Comment by rivantsov** [comment]
batch/no batch might be enabled in general, but for particular command the decision is made on the fly. The system goes for no-batch if there's something that prevents doing batch. In this case, batch with inserting identities, Postgres. Pg does NOT support multiple out params in plain SQL mode. This prevents from doing multiple inserts with generated identities in batch mode. So system automatically switches to no-batch mode. 
Look at Database.ShouldUseBatch mode method (Database class). At the end it check if driver (db server) supports specific thing: 

      if(updateSet.InsertsIdentity && !_driver.Supports(DbFeatures.OutParamsInBatchedUpdates))
        return false; 
This OutParamsInBatchUpdates is not set in Driver.Features, so that explains it
Now, why it fails - not clear/not sure. You say 'negative Id is my labeling .... ' - do you set this -1 explicitly?

**Comment by suchym** [comment]
Yes, I set a unique negative integer to each entity when new entity is inserting into the database. In case of update/delete, I keep the original value.  
Peak entity has composite primary key (SpectrumId, OrderId). OrderId has right value only SpectrumId value comes from my labeling.

**Comment by rivantsov** [comment]
So, the exc says " Key (SpectrumId)=(-1) is not present in table "Spectrum"
and you are clearly inserting bunch of -1 values there. Is -1 value correct and target with this Id exists, or it is wrong (-1) and should have been replaced by another correct value? 
Something goofy happens here, looks like combination of implicit and explicit key value manipulations (implicit - behind the scene, identity mgmt ? my guess)

**Comment by rivantsov** [comment]
btw, you say it worked before in 1.9; Pg allows output params in stored procs, but not with plain SQL. So that's why batch mode is off here - multiple identities  to insert.  It still batches multiple inserts into 1 statement as your SQL shows. - when an insert does NOT generate new identities. Well, the question now - why -1 is there? apparently thee's no record with id=-1 on the other end

**Comment by suchym** [comment]
-1 is my marker for pre-saving actions on the Spectrum entity. During saving VITA replaces it by the correct value from database.

**Comment by suchym** [comment]
Here is picture from debugger that shows changed entities from session before SaveChanges method call. Hope that help you.
![image](https://user-images.githubusercontent.com/22904904/58151721-cd0bf000-7c6a-11e9-902d-df298d3c4344.png)

**Comment by suchym** [comment]
And here is the same picture after SaveChanges call.
![image](https://user-images.githubusercontent.com/22904904/58152291-74d5ed80-7c6c-11e9-92c2-865f586d49d7.png)

**Comment by rivantsov** [comment]
Your last pci shows that after SaveChanges the SpectrumId is still -1, which is wrong. 
Ok, this is my wild guess, I've run into smth like this before. You say -1 is your own marker, so I assume you assign it explicitly, after entity is created. The problem might be that the record is tracked internally (in RecordsLoaded dictionary) using PK (as string) as a key. So I think what might be happening is: you assign -1 but record is still tracked under old value. Plus, for identity columns the column value is initialized with negative ever decreasing values, and I am afraid you messing with this value screws up the operations.  
I suggest to stop messing with PK column value. There's special field EntityRecord.CustomTag which is exactly for this purpose (sounds like) - to use by app to store some custom processing info. You can easily read/assign it: 
var rec = EntityHelper.GetRecord(myEntity);
rec.CustomTag = new MyTag(); 
var tag = rec.CustomTag; 
Try this, let's see if it works

**Comment by rivantsov** [comment]
hi
did you try it?

**Comment by suchym** [comment]
Sorry, not yet because I am preparing release for next week. It is based on
1.9.3 version, but if I have time this weekend I try it.

**Comment by suchym** [comment]
Sorry for the delay. 
I tried to made some changes in code to avoid overwriting PK in code. 
In fact I was mistake. I am not doing anything with PK. What you can see in pictures above is managed by VITA.

For clarification - there are more entities that have defined  primary key as a composite key - composed of PK  of parent entity and OrderId which is sequence number starting from 1 in the database.
In the picture above you can see that there is IPgScanNumber entity. Its parent entity is IPgSpectrum. This entity has assigned correct Id of spectrum (88) and OrderId (1). That is because there is only one scan number entity for specified spectrum.

In contrary to IPGSpectrumPeak entity where there are more records.

When I  assigned only one IPgSpectrumPeak entity  to the spectrum, saving continued but failed for  another similar entity with more records (IPgPrescreeningPeak).

So conclusion is: When there are more records with above described composite primary key, saving fails.

**Comment by rivantsov** [comment]
all right, kinda got it (the problem), will have a look and let you know. Will need to setup an experimental model for this, to mimic the conditions

**Comment by suchym** [comment]
Is there anything new with this issue?

**Comment by rivantsov** [comment]
ah sorry, was very busy with other things, will get to this by the end of this week

**Comment by suchym** [comment]
Thank you for answer. No worries.

**Comment by rivantsov** [comment]
Hi
So, I tried, build a test case with composite PK that includes identity column and ref to parent with identity. Everything works. Here is the test file, just add it to BasicTests project and run for PG. 
As you'll see, with or without batch setting, it always runs without batch because of identity columns. 
[IdentityTests2.txt](https://github.com/rivantsov/vita/files/3438251/IdentityTests2.txt)

Something else is going on. Can you pls send me c# source of entities involved and log file of failed transaction with all SQLs; send it to rivantsov AT gmail dot com

**Comment by rivantsov** [comment]
By the way, another thing. OrderId identity column you have there. From the name, it looks like it will be used to preserve the order of child records, while also being part of PK, and making it unique combination with FK column referencing parent. 
If this is the case (using to preserve order) - this is wrong assumption. The order in which you add records is not garanteed to be reflected in OrderId sequence, because SaveChanges rearranges records before sending them to DB, and it might happen that the final order of child records is altered, so you OrderId identity values messed up. 
I suggest to rethink the design if this is the case.

**Comment by rivantsov** [comment]
Finally, this thread gets too long, tired of scrolling down. Pls respond on new item/thread

**Comment by suchym** [comment]
I tried your test. It passed but  OrderId  is not 'Identity' column on my side. 
Values in the column are assigned when preparing changes for save , before 'SaveChanges' method is called. 
When I removed identity attribute from the column and slightly changed your test, the  exception was thrown: duplicate key value violates unique constraint "PK_UserPost".

**Comment by rivantsov** [comment]
can you pls send me your modified test (my test that you modified) that fails now?
thx

**Comment by rivantsov** [comment]
I think I got it, spotted the problem, will post fix asap

**Comment by rivantsov** [comment]
fixed in 2.3.1, source in release 2.3 branch
