### ISSUE TITLE
PostgreSQL , Vita 2.3.2, Intersect

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#96]
I moved to the latest version of VITA (2.3.2) and performed some tests.
Something is done wrong in latest version of VITA.
This Linq query which was successfully executed in 1.9.3. failed in 2.3.2 version.
_QUERY:_
var inQuery = Session.EntitySet<IPgIsotopicFormulaAnnotationHashTable>()
                .Where(hp => hasKeys1.Contains(hp.HashKey1))
                .Select(iht => iht.Annotation.Id)
                .Intersect(Session.EntitySet<IPgIsotopicFormulaAnnotationHashTable>()
                .Where(hp => hasKeys2.Contains(hp.HashKey2))
                .Select(iht => iht.Annotation.Id));
            var idArray = inQuery.Select(iq => iq).ToArray();

_Generated SQL in 1.9.3._
SELECT t0$."AnnotationId" AS "iq"
FROM "common"."IsotopicFormulaAnnotationHashTable" t0$
WHERE (t0$."HashKey1" = ANY(@P0))
INTERSECT
SELECT t1$."AnnotationId"
FROM "common"."IsotopicFormulaAnnotationHashTable" t1$
WHERE (t1$."HashKey2" = ANY(@P1))

_Exception in 2.3.2:_
Vita.Data.Linq.Translation.LinqTranslationException: Linq to SQL translation failed, invalid expression: **Queryable/Enumerable method Intersect not supported**. ---> System.Exception: Queryable/Enumerable method Intersect not supported.
   at Vita.Entities.Util.Throw(String message, Object[] args)
   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeQueryableCall(MethodInfo method, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(ExpressionChain expressionChain, Expression parameter, TranslationContext context)
   at Vita.Data.Linq.LinqEngine.TranslateSelectExpression(Expression linqExpr, TranslationContext context)
   at Vita.Data.Linq.LinqEngine.TranslateSelect(LinqCommand command)
   at Vita.Data.Linq.LinqEngine.Translate(LinqCommand command)
   --- End of inner exception stack trace ---
   at Vita.Data.Linq.LinqEngine.Translate(LinqCommand command)
   at Vita.Data.Sql.SqlFactory.GetLinqSql(LinqCommand command)
   at Vita.Data.Runtime.Database.ExecuteLinqSelect(EntitySession session, LinqCommand command, DataConnection conn)
   at Vita.Data.Runtime.Database.ExecuteLinqCommand(EntitySession session, LinqCommand command)
   at Vita.Data.Runtime.DataSource.ExecuteLinqCommand(EntitySession session, LinqCommand command)
   at Vita.Entities.Runtime.EntitySession.ExecuteLinqCommand(LinqCommand command, Boolean withIncludes)
   at Vita.Entities.Runtime.EntitySession.ExecuteQuery[TResult](Expression expression)
   at Vita.Entities.Model.EntityQuery`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at HighChem.MassFrontier.Data.Repositories.PgSql.SpectralTree.Annotation.PgIsotopicFormulaAnnotationRepository.GetData(IsotopicFormulaHashPair[] hashPairs) in H:\Projects\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\SpectralTree\Annotation\PgIsotopicFormulaAnnotationRepository.cs:line 76
   at HighChem.MassFrontier.Data.Repositories.PgSql.SpectralTree.Annotation.PgIsotopicFormulaAnnotationRepository.Save(IList`1 data) in H:\Projects\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\SpectralTree\Annotation\PgIsotopicFormulaAnnotationRepository.cs:line 114
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgSpectralTreeUow.<>c__DisplayClass10_0.<SaveInternal>b__0() in H:\Projects\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgSpectralTreeUow.cs:line 559
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.Measure[T,TResult](Func`1 func, TimeSpan& timeSpan) in H:\Projects\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 177
   at HighChem.MassFrontier.Data.Core.Helpers.TimeMeasure.MeasureTime[TResult](Func`1 func, TimeSpan& timeSpan) in H:\Projects\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Core\Data.Core\Helpers\TimeMeasure.cs:line 185
   at HighChem.MassFrontier.Data.Repositories.PgSql.UnitOfWork.PgSpectralTreeUow.SaveInternal(IDomainIdentifiable`1 compoundId, SpectralTreeDto dto, IEntitySession session, Boolean updateInternalCache) in H:\Projects\MF8\Private\Applications\Desktop\MassFrontierV8.Data\Infrastructure\Data.Repositories.PgSql\UnitOfWork\PgSpectralTreeUow.cs:line 501
Exception data (Vita.Data.Linq.Translation.LinqTranslationException): 
  LinqExpression = (@P0, @P1) => EntitySet<IPgIsotopicFormulaAnnotationHashTable>.Where(hp => @P0.Contains(hp.HashKey1)).Select(iht => iht.Annotation.Id).Intersect(EntitySet<IPgIsotopicFormulaAnnotationHashTable>.Where(hp => @P1.Contains(hp.HashKey2)).Select(iht => iht.Annotation.Id)).Select(iq => iq) 
  LinqQuery = Vita.Data.Linq.DynamicLinqCommand 
  entity-command = Vita.Data.Linq.DynamicLinqCommand 
  parameters = [[2932978195, 691970368, 1740157184, 710873573, 1713772501, 1730024821, 1627276448, 4050698281, 1718357399, 1582171240, 1815461953, 2442245556, 2031303844, 2642997332, 2561146013, 3940693551, 2862425036, 4031623696, 1936695889, 867050014, 2792306405, 459613826, 3967400874, 3917020366, 1073399322, 3258977724, 169004554, 3928435748, 2784882570, 1664492509, 1269822158, 1830274603, 1160100811, 1200272239, 1041842336, 438901486, 2996403417, 1743446148, 2850920641, 1375502510, 3696513883, 1679172638, 3065817943, 962602417, 3477083617, 2864285784, 2701675933, 287818531, 3888109259, 3112102349 ...], [855526334, 2959403289, 38378498, 3994461988, 3884106155, 3145436912, 1660858800, 1069921274, 3642053049, 2332942974, 2003502300, 3670000427, 2482574856, 3359129520, 2482630983, 504411196, 1868240173, 2641396947, 2117240956, 1587506973, 620692235, 3180001014, 4275345270, 2442001353, 2085812201, 4109419496, 4012156812, 3279299415, 127451365, 3476276401, 3204011965, 289164061, 1829357812, 3755955359, 295181131, 4200004658, 1019341507, 1597480346, 4099520988, 2076916782, 1288227959, 3239386113, 2025619410, 236764939, 1063864964, 2514390145, 3826469345, 1457606772, 2946980169, 115107178 ...]]

**Comment by rivantsov** [comment]
Hmm.. I probably disabled it because of some other problems in implementation; in general I think intersect is rarely used in SQL, so I thought it would do no harm
In your case - do you really need it here? seems like you can just AND two Contains expr in one WHERE clause

**Comment by suchym** [comment]
I think that I have more intersect / except and union in code .
In 1.9.3 I had no problem with these operators -  tested in both SQLServer
and PostgreSQL environment.
It is step back from my point of view . Not all queries can be easily
rewritten and it needs to take into account execution plan generated for
those queries.

**Comment by rivantsov** [comment]
OK, got it, will look to bring it back

**Comment by rivantsov** [comment]
added back support for Union, Except, Intersect
v 2.5 pushed, in master branch
